# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13af48e2c987fd8e7ccd3d7f8613d0c6cf0018704981e89daa16ade79ccd202a8a8007b116b0d860b5c6debc856d930637fae910ed83eb64ff23faa19c7e6046

test:
  secret_key_base: d2bc6aa6c0a0118247f74616bbe39c531e82762015931333cf69a0c1d7ff04c1fce1d44a6944cfc7fc2b5928890ac8b338197d2435838d7f82445bbd5b4d2f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
